id: I44A9BBFC
legacy_id: P006689
ocr_import_info:
  bdrc_scan_id: W5062
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T09:40:18'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T02:54:27.526055+00:00'
last_modified: 2022-09-04 10:59:25.650831
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W5062
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW5062
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། མི་ཕམ་རྒྱ་མཚོ།
  author: འཇུ་མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.6388666489079201
  ocr_word_median_confidence_index: 0.6700000166893005
quality: null
bases:
  I1KG8540:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8540
      total_pages: 707
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG8540.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.7071460733559305
    legacy_id: v001
  I1KG8543:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8543
      total_pages: 693
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG8543.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6628438365388996
    legacy_id: v004
  I1KG8553:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8553
      total_pages: 1023
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I1KG8553.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5508427579870826
    legacy_id: v014
  I1KG8552:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8552
      total_pages: 701
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I1KG8552.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.696680770917226
    legacy_id: v013
  I1KG8545:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8545
      total_pages: 786
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG8545.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6928756322159878
    legacy_id: v006
  I1KG8554:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8554
      total_pages: 862
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I1KG8554.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.6063645308328762
    legacy_id: v015
  I1KG8541:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8541
      total_pages: 775
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG8541.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6889299622736955
    legacy_id: v002
  I1KG8550:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8550
      total_pages: 835
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I1KG8550.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.6022851255591737
    legacy_id: v011
  I1KG8544:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8544
      total_pages: 897
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG8544.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6154282516028527
    legacy_id: v005
  I1KG8547:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8547
      total_pages: 686
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG8547.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.679961459048879
    legacy_id: v008
  I1KG8549:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8549
      total_pages: 854
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I1KG8549.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6663849150409868
    legacy_id: v010
  I1KG8551:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8551
      total_pages: 743
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I1KG8551.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6634550876615084
    legacy_id: v012
  I1KG8542:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8542
      total_pages: 880
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG8542.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6281833181915891
    legacy_id: v003
  I1KG8548:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8548
      total_pages: 856
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1KG8548.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5706577979369347
    legacy_id: v009
  I1KG8546:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8546
      total_pages: 744
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG8546.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7227731599270515
    legacy_id: v007
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
