id: I44A9BBFC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:48:13+00:00'
last_modified: '2022-06-08T06:09:51.819774+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W5062
  title: གསུང་འབུམ། མི་ཕམ་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    CD6F:
      image_group_id: I1KG8540
      title: ''
      total_pages: 707
      order: 1
      base_file: CD6F.txt
    E414:
      image_group_id: I1KG8541
      title: ''
      total_pages: 775
      order: 2
      base_file: E414.txt
    '7889':
      image_group_id: I1KG8542
      title: ''
      total_pages: 880
      order: 3
      base_file: 7889.txt
    111A:
      image_group_id: I1KG8543
      title: ''
      total_pages: 693
      order: 4
      base_file: 111A.txt
    D6ED:
      image_group_id: I1KG8544
      title: ''
      total_pages: 897
      order: 5
      base_file: D6ED.txt
    '1306':
      image_group_id: I1KG8545
      title: ''
      total_pages: 786
      order: 6
      base_file: 1306.txt
    '2233':
      image_group_id: I1KG8546
      title: ''
      total_pages: 744
      order: 7
      base_file: 2233.txt
    884D:
      image_group_id: I1KG8547
      title: ''
      total_pages: 686
      order: 8
      base_file: 884D.txt
    43EE:
      image_group_id: I1KG8548
      title: ''
      total_pages: 856
      order: 9
      base_file: 43EE.txt
    88D8:
      image_group_id: I1KG8549
      title: ''
      total_pages: 854
      order: 10
      base_file: 88D8.txt
    '5645':
      image_group_id: I1KG8550
      title: ''
      total_pages: 835
      order: 11
      base_file: 5645.txt
    2FE9:
      image_group_id: I1KG8551
      title: ''
      total_pages: 743
      order: 12
      base_file: 2FE9.txt
    DCCB:
      image_group_id: I1KG8552
      title: ''
      total_pages: 701
      order: 13
      base_file: DCCB.txt
    C0A8:
      image_group_id: I1KG8553
      title: ''
      total_pages: 1023
      order: 14
      base_file: C0A8.txt
    EC17:
      image_group_id: I1KG8554
      title: ''
      total_pages: 862
      order: 15
      base_file: EC17.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
